### ISSUE TITLE
application crash on fresh install

### ISSUE THREAD

**Issue by azeemgujjar** [pratyushpundir/laravel-buefy-preset#1]
vue.common.dev.js?4650:630 [Vue warn]: Error compiling template:

invalid expression: Unexpected token } in

    ['navbar-menu', {
        'is-active': mobileMenuOpen
    }

  Raw expression: :class="['navbar-menu', {
        'is-active': mobileMenuOpen
    }"

23 |      </div>
24 |  
25 |      <div id="primary-nav" :class="['navbar-menu', {
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^
26 |          'is-active': mobileMenuOpen
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
27 |      }">
   |  ^^^^^^

(found in <Root>)

**Comment by pratyushpundir** [comment]
Weird! I'm looking into this. Give me a few minutes please.

**Comment by azeemgujjar** [comment]
great, right now i am developing using your flavor, if you can fix this quickly then i can start my project using your repo..
i don't want to go with stupid bootstrap and react...

**Comment by umaircsstd** [comment]
Yeah facing the same issue on fresh laravel 5.8 
just follow these steps 

Run composer require pratyushpundir/laravel-buefy-preset.
Then run php artisan preset buefy. This will scaffold everything you need to replace Bootstrap with Bulma and set up your JS, SASS and Blade Views.
Install and compile your assets with yarn && yarn watch or npm install && npm run watch (but yarn is so much better!!!).

application page flickers and then console shows above mention error

**Comment by umaircsstd** [comment]
Hy bro looks like i found the issue and also fixed it 

in bulma-nav.blade.php 

line number:28
square bracket missed 

**change** 

` <div id="primary-nav" :class="['navbar-menu', {
        'is-active': mobileMenuOpen
    }">`

**to**
`<div id="primary-nav" :class="['navbar-menu', {
        'is-active': mobileMenuOpen
    }]">`

**Comment by azeemgujjar** [comment]
Thanks for the quick fix man @umaircsstd

**Comment by pratyushpundir** [comment]
Apologies for that people! Issue is fixed in v0.0.5!
